# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
FLUXCO_DE_USERNAME: nathanial-mcconnell@fluxco.de
FLUXCO_DE_PASSWORD: !yzzorderrex76?
MANDRILL_USERNAME: nathanial-mcconnell@fluxco.de
MANDRILL_API_KEY: bd8meDZzpNAoD2K5s0w1EA
MAILCHIMP_API_KEY: 51bbb048d3914f2b6367ec07059aedc8-us7
MAILCHIMP_LIST_ID: b826f8dfc6
ADMIN_EMAIL: instructor@fluxco.de
ADMIN_FIRST_NAME: Augur
ADMIN_LAST_NAME: Praetor
ADMIN_PASSWORD: !yzzorderrex76?
ROLES: [admin, instructor, user]
EMAIL_ADDRESS: hall-monitor@fluxco.de
DOMAIN: fluxco.de
FACEBOOK_KEY: 1426699447552827
FACEBOOK_SECRET: 608d2ad8735247cf0e92f2a2a7119c25
TWITTER_CONSUMER_KEY: gWiZGxhHIpckqKs95JfAlA
TWITTER_CONSUMER_SECRET: B84OmmnuvzqGiCXgot7W9Y91RZ9RjmI7MhjfSCpTQs
TWITTER_ACCESS_TOKEN: 1978348772-rvgwST9FEWSJDbnK1wNYSywTAlrCzYwcxkiz0Qp
TWITTER_ACCESS_SECRET: g05grCUE1ws6XQZ6CPWO4zYyS8aOBX5mbTjvRGqs
